### ISSUE TITLE
Do not silently convert ambiguous aminoacids

### ISSUE THREAD

**Issue by gui11aume** [Adibvafa/CodonTransformer#5]
Ambiguous aminoacids B, Z, X, J, U, O are converted to N, Q, A, L, C, K (respectively) without warning. Ambiguous aminoacids should not be accepted by default, and what to do with them should be specified by the user. For instance, the user may want to replace them with a random aminoacid in the ambiguous group, or they may pass a dictionary to specify a deterministic replacement rule, or some other option if applicable.

**Comment by Adibvafa** [comment]
Solved by PR #9.
